trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Instalar pnpm
  - script: |
      corepack enable pnpm
    displayName: 'Install pnpm'

  # Instalar dependencias
  - script: |
      pnpm install
    displayName: 'Install dependencies'

  # Ejecutar lint
  - script: |
      pnpm lint
    displayName: 'Run lint'

  # Ejecutar tests
  - script: |
      pnpm test
    displayName: 'Run tests'

  # Build
  - script: |
      pnpm build
    displayName: 'Build project'
