export { useVentas } from './useVentas';
export type {
  ModoVenta,
  Step,
  ClienteSortMode,
  ClienteOption,
  ClienteForm,
  ClienteFormErrors,
  LoteVenta,
  VentaFifoItem,
  VentaGuardadaResumen,
  VentaParcialCardAlert,
} from './useVentas';
export {
  LIMITE,
  CLIENTE_SORT_OPTIONS,
  VENTA_FILTRO_TODOS,
  CLIENTE_GENERAL,
  kg,
  money,
  toNum,
  soloDigitos,
  datosPasoVenta,
  getVentasGuidance,
  getClienteSeleccionGuidance,
  getClientePhoneError,
  getVentaSubmitMessage,
  writeVentaDraft,
  readVentaDraft,
  clearVentaDraft,
} from './useVentas';
